### ISSUE TITLE
Can't click on leaf nodes to open the corresponding code file

### ISSUE THREAD

**Issue by ADTC** [hb1998/sapling#23]
**Describe the bug**
It seems I can only click on higher level nodes to open the corresponding code file, but this doesn't work on leaf nodes.

**To Reproduce**
1. Install Extension.
2. Run it on a parent component.
3. Click on leaf/non-leaf nodes in the tree.

**Expected behavior**
Clicking on any node should open the corresponding code file

**Screenshots**

<img width="304" alt="image" src="https://github.com/hb1998/react-component-tree/assets/6047296/3c1974f8-f268-4415-88b4-1c2466e6e7e0">

I'm only able to click on the first three (that is, the non-leaf nodes) to open the corresponding code file. If I click the last three (leaf nodes), nothing happens.

**Additional context**
VS Code 
```yaml
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```
